project:
  type: website
  resources:
    - styles.css

website:
  title: "quarto-hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
